                        
services:
  stock_api:
    build: 
      context: ./api
      dockerfile: Dockerfile   
    container_name: stock_api
    image: stock_api:latest
    
    ports:
      - "8000:8000"

    env_file:
      - .env
  prometheus:
      image: prom/prometheus:latest
      command: ["--config.file=/etc/prometheus/prometheus.yml"]
      volumes:
        - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        - prom_data:/prometheus
      ports: ["9090:9090"]
      depends_on: [stock_api]
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin   # change in prod
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
      - ./monitoring/grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
      - ./monitoring/dashboards:/etc/grafana/provisioning/dashboards:ro
    ports: ["3000:3000"]
    depends_on: [prometheus]

volumes:
  prom_data:
  grafana_data: