global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "stock_api"
    metrics_path: /metrics
    static_configs:
      - targets: ["stock_api:8000"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]